//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordEntryDal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FolderScanEntities : DbContext
    {
        public FolderScanEntities()
            : base("name=FolderScanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<File> Files { get; set; }
        public virtual IDbSet<Word> Words { get; set; }
        public virtual IDbSet<WordEntry> WordEntries { get; set; }
    }
}
