//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordEntryDal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordEntry
    {
        public long Id { get; set; }
        public int FileId { get; set; }
        public int WordId { get; set; }
        public int WordIndex { get; set; }
        public int WordLine { get; set; }
    
        public virtual File File { get; set; }
        public virtual Word Word { get; set; }
    }
}
